#!/bin/sh
#
# @name Omnidirectional Tilt Coaxial Quadcopter (GZ)
#
# @type Octorotor Coaxial
# @class Copter
#
# @output Motor1 motor 1
# @output Motor2 motor 2
# @output Motor3 motor 3
# @output Motor4 motor 4
# @output Motor5 motor 5
# @output Motor6 motor 6
# @output Motor7 motor 7
# @output Motor8 motor 8
#
# @output Servo1 servo 1
# @output Servo2 servo 2
# @output Servo3 servo 3
# @output Servo4 servo 4
#
# @maintainer Carroll Lee <carroll@kaist.ac.kr>
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=omnidirectional}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default MAV_TYPE 2

param set-default CA_AIRFRAME 11
param set-default CA_METHOD 3
param set-default CA_ROTOR_COUNT 8

param set-default CA_ROTOR0_PX 0.257
param set-default CA_ROTOR0_PY 0.257
param set-default CA_ROTOR0_KM 0.05 # CCW

param set-default CA_ROTOR1_PX 0.257
param set-default CA_ROTOR1_PY -0.257
param set-default CA_ROTOR1_KM -0.05

param set-default CA_ROTOR2_PX -0.257
param set-default CA_ROTOR2_PY -0.257
param set-default CA_ROTOR2_KM 0.05

param set-default CA_ROTOR3_PX -0.257
param set-default CA_ROTOR3_PY 0.257
param set-default CA_ROTOR3_KM -0.05

param set-default CA_ROTOR4_PX 0.257
param set-default CA_ROTOR4_PY -0.257
param set-default CA_ROTOR4_KM 0.05

param set-default CA_ROTOR5_PX 0.257
param set-default CA_ROTOR5_PY 0.257
param set-default CA_ROTOR5_KM -0.05

param set-default CA_ROTOR6_PX -0.257
param set-default CA_ROTOR6_PY 0.257
param set-default CA_ROTOR6_KM 0.05

param set-default CA_ROTOR7_PX -0.257
param set-default CA_ROTOR7_PY -0.257
param set-default CA_ROTOR7_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_FUNC8 108

param set-default CA_SV_CS_COUNT 4

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

param set-default SIM_GZ_EC_DIS1 150
param set-default SIM_GZ_EC_DIS2 150
param set-default SIM_GZ_EC_DIS3 150
param set-default SIM_GZ_EC_DIS4 150
param set-default SIM_GZ_EC_DIS5 150
param set-default SIM_GZ_EC_DIS6 150
param set-default SIM_GZ_EC_DIS7 150
param set-default SIM_GZ_EC_DIS8 150

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150
param set-default SIM_GZ_EC_MIN7 150
param set-default SIM_GZ_EC_MIN8 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000
param set-default SIM_GZ_EC_MAX7 1000
param set-default SIM_GZ_EC_MAX8 1000

param set-default MPC_THR_HOVER 0.50

param set-default COM_ARM_WO_GPS 1
param set-default CBRK_IO_SAFETY 22027
param set-default CBRK_SUPPLY_CHK 894281

param set-default MPC_TILTMAX_AIR 60
param set-default MPC_TILTMAX_LND 12
param set-default MPC_MAN_TILT_MAX 60
param set-default FD_FAIL_P 0

param set-default MC_ROLL_P 3.5
param set-default MC_ROLLRATE_P 1.0
param set-default MC_PITCH_P 7.0
param set-default MC_PITCHRATE_P 1.0
param set-default MC_YAW_P 3.0
param set-default MC_YAWRATE_P 1.0
